"""Assembles the final self-contained explorer page from template.html + the
generated manifests + font files. Run after build_manifest.py.

Usage: python reports/explorer/build_page.py
Output: reports/explorer/index.html (self-contained, no external requests)
"""
import json, os, base64

HERE = os.path.dirname(os.path.abspath(__file__))


def b64_file(path):
    with open(path, 'rb') as f:
        return base64.b64encode(f.read()).decode('ascii')


def main():
    template = open(os.path.join(HERE, 'template.html'), encoding='utf-8').read()

    grid = json.load(open(os.path.join(HERE, 'explorer_manifest.json')))
    hero = json.load(open(os.path.join(HERE, 'hero_pair.json')))
    stats = json.load(open(os.path.join(HERE, 'stats_manifest.json')))
    daynight = json.load(open(os.path.join(HERE, 'daynight_manifest.json')))
    data_js = (
        '// AUTO-GENERATED by build_manifest.py — do not hand-edit\n'
        'window.EXPLORER_DATA = ' + json.dumps(grid) + ';\n'
        'window.HERO_DATA = ' + json.dumps(hero) + ';\n'
        'window.STATS_DATA = ' + json.dumps(stats) + ';\n'
        'window.DAYNIGHT_DATA = ' + json.dumps(daynight) + ';\n'
    )
    template = template.replace('__DATA_JS__', data_js)

    fonts_dir = os.path.join(HERE, 'fonts')
    template = template.replace('__FONT_BARLOW700__', b64_file(os.path.join(fonts_dir, 'barlow700.ttf')))
    template = template.replace('__FONT_SOURCESERIF400__', b64_file(os.path.join(fonts_dir, 'sourceserif400.ttf')))
    template = template.replace('__FONT_JBMONO400__', b64_file(os.path.join(fonts_dir, 'jbmono400.ttf')))
    template = template.replace('__FONT_JBMONO500__', b64_file(os.path.join(fonts_dir, 'jbmono500.ttf')))

    out_path = os.path.join(HERE, 'index.html')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(template)
    print('wrote', out_path, '| size MB:', round(os.path.getsize(out_path) / 1e6, 2))


if __name__ == '__main__':
    main()
